# Generated by Django 4.2.16 on 2024-10-15 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('consecutivo', models.AutoField(primary_key=True, serialize=False)),
                ('creado_por', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion_problema', models.TextField()),
                ('numero_activo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(max_length=100)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitud')),
            ],
        ),
    ]
